In [1]:
#Import Dependencies
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import time
import pprint

# Import API key
from api_key import g_key
g_key = g_key

In [2]:
#Load in CSV made from WeatherPY
file = "output_data/weather_data.csv"
dataframe_data = pd.read_csv(file)
df = pd.DataFrame(dataframe_data)
del df["Unnamed: 0"]
df

,City,Country,Date,Latitude,Longitude,Temperature,Humidity,Clouds,Wind Speed
0,Hasaki,JP,1660681118,35.7333,140.8333,81.00,86.0,99.0,1.48
1,Sitka,US,1660681120,57.0531,-135.3300,66.09,59.0,100.0,14.97
2,Ziro,IN,1660681122,27.6333,93.8333,61.12,99.0,95.0,0.85
3,Abnūb,EG,1660681124,27.2696,31.1511,89.69,25.0,0.0,11.77
4,Kaitangata,NZ,1660681126,-46.2817,169.8464,47.75,96.0,100.0,0.29
...,...,...,...,...,...,...,...,...,...
593,Flin Flon,CA,1660682291,54.7682,-101.8650,85.84,37.0,40.0,12.66
594,Aban,RU,1660682293,56.6700,96.0600,47.91,97.0,100.0,9.44
595,Mae Sot,TH,1660682295,16.7167,98.5667,77.41,99.0,100.0,2.15
596,Amga,RU,1660682297,60.8953,131.9608,53.64,86.0,87.0,2.55
597,Road Town,VG,1660681863,18.4167,-64.6167,86.04,70.0,40.0,8.05

In [3]:
#Configure GMaps
gmaps.configure(api_key=g_key) 

#Determine Locations
locations = df[["Latitude", "Longitude"]]

#Provide Weights Param
weights = df["Humidity"]

#Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=weights,dissipating=False, max_intensity=weights.max(),point_radius=1)

# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

In [4]:
#Create DataFrame with the most desireable conditions
#Shout Out to William Vann for telling me about the vetween statement during Project 1
vacation_df = df[df["Humidity"].between(40,60)]
vacation_df = vacation_df[vacation_df["Temperature"].between(65,85)]
vacation_df = vacation_df[vacation_df["Clouds"] < 60]
vacation_df = vacation_df[vacation_df["Wind Speed"] < 12]
vacation_df

,City,Country,Date,Latitude,Longitude,Temperature,Humidity,Clouds,Wind Speed
33,Winslow,US,1660681033,35.0242,-110.6974,82.58,47.0,0.0,3.44
38,Avarua,CK,1660680911,-21.2078,-159.7750,71.65,49.0,40.0,11.50
59,Bethel,US,1660681237,41.3712,-73.4140,81.93,40.0,20.0,11.50
91,Hay River,CA,1660681206,60.8156,-115.7999,76.98,57.0,40.0,10.36
124,Guerrero Negro,MX,1660681359,27.9769,-114.0611,84.74,48.0,13.0,11.50
202,Broome,US,1660681518,42.2506,-75.8330,78.42,51.0,40.0,6.91
208,Moose Factory,CA,1660681531,51.2585,-80.6094,73.38,49.0,0.0,11.50
234,Plainview,US,1660681580,40.7765,-73.4673,80.15,48.0,20.0,4.61
297,Ingham,US,1660681705,42.6000,-84.3833,77.86,55.0,40.0,8.05
332,Ajdabiya,LY,1660681777,30.7554,20.2263,84.69,43.0,0.0,11.21
335,Port Alberni,CA,1660681784,49.2413,-124.8028,81.95,46.0,0.0,3.00
353,Pánormos,GR,1660681821,35.4182,24.6909,74.97,57.0,0.0,4.07
354,Portland,US,1660681660,45.5234,-122.6762,82.60,47.0,20.0,9.22
371,‘Ewa Beach,US,1660681557,21.3156,-158.0072,84.69,53.0,0.0,5.75
399,Antequera,ES,1660681906,37.0194,-4.5612,80.89,49.0,2.0,4.92
406,Saint-Augustin,CA,1660681920,51.2260,-58.6502,74.89,40.0,2.0,8.70
411,Shitanjing,CN,1660681930,39.2342,106.3439,73.45,60.0,27.0,7.81
416,Marmaris,TR,1660681844,36.8550,28.2742,79.11,57.0,0.0,5.53
433,San Cristobal,VE,1660681975,7.7669,-72.2250,73.58,58.0,51.0,5.12
435,Arroyo de la Encomienda,ES,1660681978,41.6096,-4.7969,67.59,54.0,0.0,8.05
439,Campbellton,CA,1660681986,48.0075,-66.6727,73.85,54.0,3.0,7.90
587,Half Moon Bay,US,1660682280,37.4636,-122.4286,82.69,57.0,0.0,6.91

In [11]:
#Store into hotel_df
hotel_df = vacation_df.reset_index()
del hotel_df["index"]
hotel_df["Hotel Name"] = ""
hotel_df

,City,Country,Date,Latitude,Longitude,Temperature,Humidity,Clouds,Wind Speed,Hotel Name
0,Winslow,US,1660681033,35.0242,-110.6974,82.58,47.0,0.0,3.44,
1,Avarua,CK,1660680911,-21.2078,-159.7750,71.65,49.0,40.0,11.50,
2,Bethel,US,1660681237,41.3712,-73.4140,81.93,40.0,20.0,11.50,
3,Hay River,CA,1660681206,60.8156,-115.7999,76.98,57.0,40.0,10.36,
4,Guerrero Negro,MX,1660681359,27.9769,-114.0611,84.74,48.0,13.0,11.50,
5,Broome,US,1660681518,42.2506,-75.8330,78.42,51.0,40.0,6.91,
6,Moose Factory,CA,1660681531,51.2585,-80.6094,73.38,49.0,0.0,11.50,
7,Plainview,US,1660681580,40.7765,-73.4673,80.15,48.0,20.0,4.61,
8,Ingham,US,1660681705,42.6000,-84.3833,77.86,55.0,40.0,8.05,
9,Ajdabiya,LY,1660681777,30.7554,20.2263,84.69,43.0,0.0,11.21,
10,Port Alberni,CA,1660681784,49.2413,-124.8028,81.95,46.0,0.0,3.00,
11,Pánormos,GR,1660681821,35.4182,24.6909,74.97,57.0,0.0,4.07,
12,Portland,US,1660681660,45.5234,-122.6762,82.60,47.0,20.0,9.22,
13,‘Ewa Beach,US,1660681557,21.3156,-158.0072,84.69,53.0,0.0,5.75,
14,Antequera,ES,1660681906,37.0194,-4.5612,80.89,49.0,2.0,4.92,
15,Saint-Augustin,CA,1660681920,51.2260,-58.6502,74.89,40.0,2.0,8.70,
16,Shitanjing,CN,1660681930,39.2342,106.3439,73.45,60.0,27.0,7.81,
17,Marmaris,TR,1660681844,36.8550,28.2742,79.11,57.0,0.0,5.53,
18,San Cristobal,VE,1660681975,7.7669,-72.2250,73.58,58.0,51.0,5.12,
19,Arroyo de la Encomienda,ES,1660681978,41.6096,-4.7969,67.59,54.0,0.0,8.05,
20,Campbellton,CA,1660681986,48.0075,-66.6727,73.85,54.0,3.0,7.90,
21,Half Moon Bay,US,1660682280,37.4636,-122.4286,82.69,57.0,0.0,6.91,

In [25]:
#Google Places API Set Up
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

params = {
    "location": "0,0",
    "radius": 5000,
    "types": "lodging",
    "keyword": "hotel",
    "key": g_key
}

pp = pprint.PrettyPrinter(indent=4)

for index, row in hotel_df.iterrows():
    
    lat = row["Latitude"]
    long = row["Longitude"]
    
    params["location"] = f"{lat},{long}"
    
    hotel_response = requests.get(base_url, params=params)
    hotel_json = hotel_response.json()
    
    #pp.pprint(hotel_json)
    
    try:
    
        hotel_df.loc[index, "Hotel Name"] = hotel_json["results"][0]["name"]
        
    except(IndexError):
        
        hotel_df.loc[index, "Hotel Name"] = "NaN"
        continue
        
    finally:
    
        time.sleep(1.5)

In [27]:
#Drop any row where hotel was not found
hotel_df = hotel_df[hotel_df["Hotel Name"] != "NaN"]
hotel_df

,City,Country,Date,Latitude,Longitude,Temperature,Humidity,Clouds,Wind Speed,Hotel Name
0,Winslow,US,1660681033,35.0242,-110.6974,82.58,47.0,0.0,3.44,La Posada Hotel
1,Avarua,CK,1660680911,-21.2078,-159.7750,71.65,49.0,40.0,11.50,The Islander Hotel
2,Bethel,US,1660681237,41.3712,-73.4140,81.93,40.0,20.0,11.50,Hampton Inn Danbury
3,Hay River,CA,1660681206,60.8156,-115.7999,76.98,57.0,40.0,10.36,Ptarmigan Inn
4,Guerrero Negro,MX,1660681359,27.9769,-114.0611,84.74,48.0,13.0,11.50,The Halfway Inn
6,Moose Factory,CA,1660681531,51.2585,-80.6094,73.38,49.0,0.0,11.50,Super 8 by Wyndham Moosonee
7,Plainview,US,1660681580,40.7765,-73.4673,80.15,48.0,20.0,4.61,"Holiday Inn Plainview-Long Island, an IHG Hotel"
9,Ajdabiya,LY,1660681777,30.7554,20.2263,84.69,43.0,0.0,11.21,الجلاء للشقق الفندقية
10,Port Alberni,CA,1660681784,49.2413,-124.8028,81.95,46.0,0.0,3.00,Best Western Plus Barclay Hotel
11,Pánormos,GR,1660681821,35.4182,24.6909,74.97,57.0,0.0,4.07,The Royal Blue Resort
12,Portland,US,1660681660,45.5234,-122.6762,82.60,47.0,20.0,9.22,River's Edge Hotel
13,‘Ewa Beach,US,1660681557,21.3156,-158.0072,84.69,53.0,0.0,5.75,Hampton Inn & Suites Oahu/Kapolei
14,Antequera,ES,1660681906,37.0194,-4.5612,80.89,49.0,2.0,4.92,Convento de la Magdalena
16,Shitanjing,CN,1660681930,39.2342,106.3439,73.45,60.0,27.0,7.81,Yingbin Hotel
17,Marmaris,TR,1660681844,36.8550,28.2742,79.11,57.0,0.0,5.53,Orka Lotus Beach
18,San Cristobal,VE,1660681975,7.7669,-72.2250,73.58,58.0,51.0,5.12,Lidotel Hotel Boutique San Cristobal
19,Arroyo de la Encomienda,ES,1660681978,41.6096,-4.7969,67.59,54.0,0.0,8.05,Hotel El Jardín de la Abadía
20,Campbellton,CA,1660681986,48.0075,-66.6727,73.85,54.0,3.0,7.90,Quality Hotel & Conference Centre
21,Half Moon Bay,US,1660682280,37.4636,-122.4286,82.69,57.0,0.0,6.91,Beach House Hotel

In [28]:
# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longitude"]]

In [29]:
#Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations=locations, display_info_box=True, info_box_content=hotel_info)

#Add the layer to the map
fig.add_layer(markers)

fig

Figure(layout=FigureLayout(height='420px'))